### ISSUE TITLE
hakrevdns: command not found

### ISSUE THREAD

**Issue by mrofisr** [hakluke/hakrevdns#1]
hakrevdns: command not found

what should I do?

**Comment by keyboardcrunch** [comment]
@mrofisr Is your GOPATH and environmental variable path configured, explicitly $GOPATH/bin ?
https://github.com/golang/go/wiki/SettingGOPATH

I was able to go get && execute hakrevdns on Ubuntu 19.10 w/Go 1.13.1

**Comment by ghost** [comment]
go to dir /root/go/bin (or to your go env-t PATH dir)
run command ./hakrevdns 192.168.0/24

**Comment by mrofisr** [comment]
ok i cant try it. Thanks sir
